# Generated by Django 5.1.5 on 2025-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=50)),
                ('online', models.BooleanField(verbose_name='Статус онлайна')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
